---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-cm
  namespace: argo
  labels:
    app: transformation
    component: ingress2event-time
data:
  {{- toYaml .Values.config | nindent 2 }}
