apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: {{ .Values.appName }}-cron-wf
  namespace: argo
  labels:
    app: transformation
    component: ingress2event-time
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: "{{ .Values.concurrencyPolicy }}"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  workflowSpec:
    entrypoint: cron-tasks
    templates:
    - name: cron-tasks
      dag:
        tasks:
        - name: transform-ingress2event-time
          templateRef:
            name: {{ .Values.appName }}-wf-tp
            template: transformation
          {{- if .Values.transformationparams.datestring }}
          arguments:
            parameters:
            - name: date-string
              value: {{ .Values.transformationparams.datestring }}
          {{- end }}
